http:
  routers:
    gitea:
      rule: "Host(`gitea.mysite.com`)"
      entryPoints:
        - websecure
      service: gitea
      tls:
        certResolver: letsencrypt
      middlewares:
        - default-security
        - default-compress
        - default-retry
        - gitea-rate-limit
      
    # Redirect www to non-www
    gitea-www:
      rule: "Host(`www.gitea.mysite.com`)"
      entryPoints:
        - websecure
      service: gitea
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-non-www

  services:
    gitea:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:30008"
        passHostHeader: true
        healthCheck:
          path: /api/healthz
          interval: "30s"
          timeout: "5s"
          scheme: http
        serversTransport: default-transport

  middlewares:
    gitea-rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: "1s"
    
    redirect-to-non-www:
      redirectRegex:
        regex: "https://www.gitea.mysite.com/(.*)"
        replacement: "https://gitea.mysite.com/${1}"
        permanent: true

  serversTransports:
    default-transport:
      forwardingTimeouts:
        dialTimeout: "30s"
        responseHeaderTimeout: "30s"
        idleConnTimeout: "90s"
      maxIdleConnsPerHost: 32