# Global Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# EntryPoints Configuration
entryPoints:
  web:
    address: ":80"
    http:
      # Redirect to HTTPS
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    # HTTP/3 configuration for Traefik v3.5
    http3:
      advertisedPort: 443
    # QUIC configuration (properly structured)
    # Note: In Traefik v3.5, quic is configured within http3
    # If you need specific QUIC settings, uncomment and adjust:
    # quic:
    #   maxIdleTimeout: 30s
    #   maxIncomingStreams: 100
    #   connIdLength: 8

# Certificate Resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /data/acme.json
      keyType: RSA4096
      httpChallenge:
        entryPoint: web

# API and Dashboard Configuration
api:
  dashboard: true
  debug: false

# Log Configuration
log:
  level: ${LOG_LEVEL:-INFO}
  format: json
  filePath: /logs/traefik.log

# Access Log Configuration
accessLog:
  filePath: /logs/access.log
  format: json
  bufferingSize: 100
  fields:
    defaultMode: keep
    names:
      Authorization: drop
    headers:
      defaultMode: keep
      names:
        Authorization: drop

# Providers Configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    directory: /etc/traefik/config/dynamic
    watch: true