name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # https://github.com/docker/setup-compose-action
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    #- name: Set up Docker Buildx
    #  uses: docker/setup-buildx-action@v3
#
    #- name: Install Docker Compose
    #  run: |
    #    sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #    sudo chmod +x /usr/local/bin/docker-compose
    #    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    
    - name: Prepare environment
      run: |
        cp .env.example .env
        mkdir -p config/dynamic
    
    - name: Validate docker-compose configuration
      run: |
        docker-compose config
    
    - name: Validate Traefik configuration
      run: |
        # Create a test config without environment variables for validation
        cp config/traefik.yml config/traefik-test.yml
        sed -i 's/${LOG_LEVEL:-INFO}/INFO/g' config/traefik-test.yml
        sed -i 's/${ACME_EMAIL}/test@example.com/g' config/traefik-test.yml
        sed -i 's/${LOG_LEVEL:-INFO}/INFO/g' config/traefik-test.yml
        
        docker run --rm \
          -v $(pwd)/config:/etc/traefik \
          traefik:v3.5 \
          traefik --configFile=/etc/traefik/traefik-test.yml