name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.39.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    
    - name: Prepare environment
      run: |
        cp .env.example .env
        mkdir -p config/dynamic
    
    - name: Validate docker-compose configuration
      run: |
        docker-compose config
    
    - name: Validate Traefik configuration
      run: |
        docker run --rm \
          -v $(pwd)/config:/etc/traefik \
          -v $(pwd)/.env:/run/secrets/env \
          traefik:v3.5 \
          traefik --configFile=/etc/traefik/traefik.yml