# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      TRAEFIK_VERSION: v3.5
      LOG_LEVEL: INFO
      ACME_EMAIL: test@example.com
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    
    - name: Prepare environment
      run: |
        mkdir -p config/dynamic data logs
        
        cat > .env << EOF
        TRAEFIK_VERSION=${{ env.TRAEFIK_VERSION }}
        LOG_LEVEL=${{ env.LOG_LEVEL }}
        ACME_EMAIL=${{ env.ACME_EMAIL }}
        TRAEFIK_DASHBOARD_CREDENTIALS=test:$$apr1$$hashedvalue
        TRAEFIK_DASHBOARD_DOMAIN=test.example.com
        TRAEFIK_CONFIG=./config
        TRAEFIK_DATA=./data
        TRAEFIK_LOGS=./logs
        ACME_CHALLENGE_TYPE=
        CLOUDFLARE_EMAIL=
        CLOUDFLARE_API_KEY=
        CLOUDFLARE_DNS_API_TOKEN=
        NAMECHEAP_API_USER=
        NAMECHEAP_API_KEY=
        EOF
    
    - name: Validate docker-compose configuration
      run: |
        docker-compose config > /dev/null
        echo "✓ docker-compose configuration is valid"
    
    - name: Validate Traefik static configuration file
      run: |
        # Create a clean version of traefik.yml for validation
        cp config/traefik.yml config/traefik-validate.yml
        
        # Substitute all environment variables
        sed -i "s/\${LOG_LEVEL:-INFO}/${{ env.LOG_LEVEL }}/g" config/traefik-validate.yml
        sed -i "s/\${ACME_EMAIL}/${{ env.ACME_EMAIL }}/g" config/traefik-validate.yml
        
        # Remove any remaining environment variable references that might cause issues
        sed -i '/\${.*}/d' config/traefik-validate.yml
        
        echo "Validating traefik configuration file..."
        timeout 30s docker run --rm \
          -v $(pwd)/config:/etc/traefik \
          traefik:${{ env.TRAEFIK_VERSION }} \
          traefik --configFile=/etc/traefik/traefik-validate.yml
        
        echo "✓ Traefik static configuration is valid"
    
    - name: Test docker-compose startup (dry run)
      run: |
        echo "Testing docker-compose startup..."
        timeout 30s docker-compose up --no-start
        echo "docker-compose can start successfully"